# Generated by Django 3.2.7 on 2021-09-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='gradudated',
            new_name='graduated',
        ),
        migrations.AddField(
            model_name='student',
            name='passed_second_or_third_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(choices=[('CNA', 'Certified Nurse Assistant'), ('HHA', 'Home Health Aide'), ('SG', 'Security Guard'), ('ESOL', 'English to Speakers of Other Language')], max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('CNA', 'Certified Nurse Assistant'), ('HHA', 'Home Health Aide'), ('SG', 'Security Guard'), ('ESOL', 'English to Speakers of Other Language')], max_length=4),
        ),
    ]
