# Generated by Django 3.2.7 on 2021-09-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20210922_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='employment_address',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
