# Generated by Django 3.2.7 on 2021-09-29 23:27

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20210929_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='starting_wage',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=4, null=True),
        ),
    ]
