# Generated by Django 3.2.7 on 2021-09-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_student_google_sheet_migrated'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='google_sheet_migration_issue',
            field=models.CharField(blank=True, choices=[('POST', 'Could not add new record to Google Sheet'), ('PUT', 'Could not update existing record on Google Sheet'), ('DEL', 'Could not delete existing record on Google Sheet')], max_length=4),
        ),
    ]
