# Generated by Django 3.2.7 on 2021-09-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_alter_student_employment_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='position',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
