# Generated by Django 3.2.7 on 2021-10-04 17:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_account_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='programs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('CNA', 'Certified Nurse Assistant'), ('HHA', 'Home Health Aide'), ('SG', 'Security Guard'), ('CG', 'Caregiver'), ('ESOL', 'English to Speakers of Other Language'), ('BLS', 'Basic Life Support'), ('HSFA', 'Heartsaver First Aid')], max_length=5), null=True, size=None),
        ),
    ]
