# Generated by Django 3.2.7 on 2021-10-09 23:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_alter_student_description_of_attempts_to_contact_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='approval_entities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('AHA', 'American Heart Association'), ('CDPH', 'California Department of Public Health'), ('BPPE', 'Bureau of Postsecondary and for Private Education'), ('BSIS', 'Bureau of Security and Investigative Services')], max_length=10), size=None),
        ),
    ]
