# Generated by Django 3.2.7 on 2021-10-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_alter_student_description_of_attempts_to_contact_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
