# Generated by Django 3.2.7 on 2021-11-12 16:01

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='starting_wage',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=10, null=True),
        ),
    ]
