# Generated by Django 3.2.7 on 2022-03-15 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_alter_student_starting_wage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Education Programs'},
        ),
        migrations.AlterModelOptions(
            name='rotation',
            options={'verbose_name': 'Program Rotations or Classes'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Main/Satellite Schools'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Students and Graduates'},
        ),
    ]
