# Generated by Django 3.2.7 on 2022-05-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_alter_student_starting_wage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Education Program'},
        ),
        migrations.AlterModelOptions(
            name='rotation',
            options={'verbose_name': 'Program Rotations or Classe'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Main/Satellite School'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Students and Graduate'},
        ),
    ]
