# Generated by Django 3.2.7 on 2022-03-15 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Clientele'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': "Client's notes"},
        ),
    ]
