# Generated by Django 3.2.7 on 2022-12-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20220314_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': "Client's note"},
        ),
    ]
