# Generated by Django 3.2.7 on 2021-10-06 19:17

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+1-888-888-8888'. Up to 15 digits allowed.", regex='^(\\+\\d-)?\\d{3}-\\d{3}-\\d{4}$')])),
                ('is_office', models.BooleanField(default=False)),
                ('is_recruit', models.BooleanField(default=False)),
                ('is_instructor', models.BooleanField(default=False)),
                ('programs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('CNA', 'Certified Nurse Assistant'), ('HHA', 'Home Health Aide'), ('SG', 'Security Guard'), ('CG', 'Caregiver'), ('ESOL', 'English to Speakers of Other Language'), ('BLS', 'Basic Life Support'), ('HSFA', 'Heartsaver First Aid')], max_length=5), blank=True, null=True, size=None)),
                ('school_name', models.CharField(choices=[('STI', 'Select Therapy Institute')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
