# Generated by Django 3.2.7 on 2021-10-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='school_name',
            field=models.CharField(blank=True, choices=[('STI', 'Select Therapy Institute')], max_length=10),
        ),
    ]
